# Wire up travis
language: "python"

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

install:
    - "pip install -r develop-requirements.txt"

script: "py.test"

notifications:
  email:
    - "commande.romain+decorrelate@gmail.com"
